[package]
name = "entity"
version = "0.1.0"
edition = "2021"

[dependencies]
# Add dependencies needed for your entity module, such as sea-orm.
sea-orm = { version = "1.1.0", features = ["with-serde"] }
rocket = "0.5.1"
serde = { version = "1.0", features = ["derive"] }
