//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::email::Entity as Email;
pub use super::email_file::Entity as EmailFile;
pub use super::group::Entity as Group;
pub use super::group_member::Entity as GroupMember;
pub use super::receiver::Entity as Receiver;
pub use super::user::Entity as User;
